services:
  - type: web
    name: crv-front-operation
    env: static
    region: frankfurt
    plan: free
    branch: mission/SLA_FULL_COVERAGE_FRONT
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
